### ISSUE TITLE
Ce date trebuie sa dau la banca ca sa pot conecta ?

### ISSUE THREAD

**Issue by dumy** [alexminza/wc-moldovaagroindbank#1]
Am instalat Aceasta extensie, doar ca tranzact ID nu merge
Contractul cu banca deja este facut.
Ce date trebuie sa dau ip de la server si inca ce ?

**Comment by alexminza** [comment]
@dumy MAIB va pune la dispozitie toate datele de conectare dupa ce semnati contractul.

`readme.txt`
> **Where can I get the Connection Settings data?**
> The connection settings and merchant data are provided by Moldova Agroindbank. This data is used by the plugin to connect to the Moldova Agroindbank payment gateway and process the card transactions. Please see [www.maib.md](https://www.maib.md) and contact [cards@maib.md](mailto:cards@maib.md) for details.

**Comment by dumy** [comment]
@alexminza  Salutare si respect pentru acest plugin 

Doar ca ei mi-au oferit doar 

> URL a serverului de test:

Merchant: https://ecomm.maib.md:4499/ecomm2/MerchantHandler

Client:  https://ecomm.maib.md:7443/ecomm2/ClientHandler


Dar in wordpress la setari apoi cere  **Parolă cheie privată** De unde pot sa eu acesta. Ca eu am intrebat pe ei dar o spus ca o activat serviciul si link alea care mi-au trimis. 

Multumesc

**Comment by alexminza** [comment]
Conform instructiunilor din documentatia ECOMMERCE de la MAIB:

`openssl pkcs12 -in YOURPFX.pfx -nocerts -out key.pem`
`openssl pkcs12 -in YOURPFX.pfx -clcerts -nokeys -out pcert.pem`
`openssl pkcs12 -in YOURPFX.pfx -cacerts -nokeys -out cacert.pem`

Referinta: https://www.openssl.org/docs/man1.1.0/apps/pkcs12.html

**Comment by alexminza** [comment]
Pentru a testa conexiunea:

`openssl s_client -connect ecomm.maib.md:4499 -key key.pem -cert pcert.pem -CAfile cacert.pem`

OR

`curl --key key.pem --cert pcert.pem https://ecomm.maib.md:4499`

**Comment by dumy** [comment]
Multumesc, sper sa ma ajute :D asteptam cu sufletul la gura

**Comment by dumy** [comment]
Nu au instructiunile, E doar fiserul cu key si link-urile 


> URL a serverului de test:
> 
> Merchant: https://ecomm.maib.md:4499/ecomm2/MerchantHandler
> 
> Client:   https://ecomm.maib.md:7443/ecomm2/ClientHandler
> 
> Pentru inceperea testarilor si acces la serverele noastre avem nevoie de:
> 
> a. IP serverului de test
> 
> b. Callback URL. Si deamu explicatii aiurite

**Dar unde trebuie de plasat  fisierele pem ?** Eu folosesc DigitalOcean cu ubuntu 18.04
Si parola care o pun eu cea nou de pem, acea trebuie de folosit in pluginul tau ?

Ma scuzi te rog frumos, Am facut o mica ### donatie din putinul meu 

Sunt foarte recunoscator.
