### ISSUE TITLE
Need to update gateway endpoints

### ISSUE THREAD

**Issue by davidfilat** [alexminza/wc-moldovaagroindbank#17]
Banca preconizează migrarea platformei eCommerce la o noua versiune a protocolului 3D-Secure.
Pentru aceasta, din partea Dvs., sunt necesari de îndeplinit cîțiva pași pentru a corespunde acestui nou protocol.
Din punct de vedere tehnic va fi necesar de a schimba adresele URL ECOMM SERVER, primite anterior de la banca (Merchant și Client), în modulul de plată a paginii web de acceptare a plăților în mediu online..

Deci, pentru plățile în regim de producție vă rog să modificați end-point gateway_ului de plată a internet magazinului pe care îl administrați, după cum urmează:

Merchant handler:
https://maib.ecommerce.md:11440/ecomm01/MerchantHandler

Client handler:
https://maib.ecommerce.md:443/ecomm01/ClientHandler

În rest setările rămîn neschimbate.

După efectuare setărilor corespunzătoare vă rog să ne anunțați pe e-mail.

P.S. Vă rugăm să efectuați modificările pînă la data de 15 iunie 2021

**Comment by alexminza** [comment]
Before an updated version of the plugin is published - please make the following changes in the code of the plugin on your server to test it with the new bank payment gateway:

- In the `/wc-moldovaagroindbank.php` file change `https://ecomm.maib.md:4455` with `https://maib.ecommerce.md:11440` and `https://ecomm.maib.md/ecomm2/ClientHandler` with `https://maib.ecommerce.md:443/ecomm01/ClientHandler`
- In the `/vendor/fruitware/maib-api/Fruitware/MaibApi/MaibDescription.php` file change all occurrences of `/ecomm2/MerchantHandler` with /ecomm01/MerchantHandler

**Comment by davidfilat** [comment]
Am modificat și am efectuat o plată de test, dar plata a eșuat:
<img width="284" alt="image" src="https://user-images.githubusercontent.com/1475163/119976184-663f1100-bfbf-11eb-828a-d7e48be0a64b.png">

**Comment by davidfilat** [comment]
<img width="1158" alt="CleanShot 2021-05-28 at 15 04 07@2x" src="https://user-images.githubusercontent.com/1475163/119981147-f8e2ae80-bfc5-11eb-8760-5a0108403a90.png">

**Comment by alexminza** [comment]
@davidfilat full debug logs are needed to be able to understand what is happening on your specific system.

**Comment by davidfilat** [comment]
@alexminza The bank support service has replied. It seems it was an issue on their side. It is fixed now and works fine. Thank you!

**Comment by alexminza** [comment]
New version published:

- https://github.com/alexminza/wc-moldovaagroindbank/releases/tag/v1.2.1
- https://wordpress.org/plugins/wc-moldovaagroindbank/
