### ISSUE TITLE
Transaction ID not received from Moldova Agroindbank

### ISSUE THREAD

**Issue by cnelindiahwe** [alexminza/wc-moldovaagroindbank#2]
Plugin is showing “Transaction ID” error.

Link here
https://webpay.pcfirstaid.com/dp/shop/

I have setup the plugin properly.

Screenshot:
https://screenshots.firefox.com/7tGDhKtBUp22nuHK/webpay.pcfirstaid.com

And i added “Private key passphrase” from Cpanel to plugin setting.

Screenshot:
http://cnelindia.com/support/admin/uploads/1590847110-s2.png

Please check it how we can fix this issue?

I am waiting your response.

Thanks

**Comment by alexminza** [comment]
@cnelindiahwe it seems from your screenshot that you have not properly configures the PEM certificates/key. You need to upload the keys to your web server, set file system permissions to properly secure the files and configure them in the plugin settings by providing the full path to the files.

**Comment by alexminza** [comment]
There is a newer version under development that will make this setup process easier for beginners, but the current version requires some fair knowledge of the OS and certificates/keys configuration to configure the plugin.

**Comment by cnelindiahwe** [comment]
Any idea on how to secure the files and configure them in the plugin settings?

I have done setup the private key to this way. Please check the screenshot.
![s1](https://user-images.githubusercontent.com/10735803/49368465-c4ebe280-f714-11e8-83da-5e6647846821.png)
![s3](https://user-images.githubusercontent.com/10735803/49368475-cae1c380-f714-11e8-92a7-cd3514fc8709.png)

But gateway still not working.

Where i am wrong?

**Comment by alexminza** [comment]
You need to upload the certificate and private key files to the web server and configure the file paths in the plugin settings. Currently, you have just some default values like cacert.pem, pcert.pem, key.pem.

PS: You should delete the screenshot with your private key and keep it strictly private and secured.

**Comment by alexminza** [comment]
There will be a new version of the plugin soon, which will allow for easier certificates configuration for beginners - directly uploading the PFX certificate received from the bank. Stay tuned!

**Comment by alexminza** [comment]
@cnelindiahwe get the new plugin version 1.1 from [WordPress.org](https://wordpress.org/plugins/wc-moldovaagroindbank/) and configure the bank connection with the new improved and simplified setup interface.

**Comment by cnelindiahwe** [comment]
Hello,

I updated plugin to latest version 1.1.

I successfully uploaded my (0149583.pfx) file in plugin setting.
Please check screenshot in below.

<img src="http://bit.ly/2PyVXsb">
<img src="http://bit.ly/2PyeQLK">

Please check path of .pem files, Is it ok or not?
But plugin following error are still showing.

"Certificate Authority (CA) bundle: Invalid value
Client certificate file: Invalid value
Private key file: Invalid value"

Please can you help me?  What i am missing now?

Thanks
Siyaram

**Comment by cnelindiahwe** [comment]
Hello,

I seen following installation notes on here (https://wordpress.org/plugins/wc-moldovaagroindbank/) 

Configure the plugin Connection Settings by performing one of the following steps:
BASIC: Upload the PFX client certificate file received from the bank
ADVANCED: Convert and upload the private key and certificates PEM files 
to the server and securely set up the owner and file system permissions

=> I uploaded done PFX file.
=>  I don't see PEM file on over server cpanel. How i can get these file? 
The main issue of these files.

Thanks

**Comment by alexminza** [comment]
@cnelindiahwe it seems that you are confusing the cPanel SSL/TLS certificates which are used to enable HTTPS on your website with certificates used by the plugin to connect securely to the bank.

You need to use the plugin settings page to configure the certificates received from the bank.
After you have uploaded the PFX file (and set up the certificate password) you need to make a test payment.

https://wordpress.org/plugins/wc-moldovaagroindbank/#installation

**Comment by cnelindiahwe** [comment]
Okay, Then i uploaded PFX file only and save  setting.
But following are showing in logs.
<img src="http://bit.ly/2rxWj97">

**Comment by alexminza** [comment]
You need to upload the PFX certificate received from the bank.
Once again - do not confuse HTTPS certificates for your websites, and the certificates from your bank.
