### ISSUE TITLE
Payments fail, even though no 3d secure confirmation is required

### ISSUE THREAD

**Issue by davidfilat** [alexminza/wc-moldovaagroindbank#21]
<img width="1844" alt="CleanShot 2022-01-18 at 10 44 40@2x" src="https://user-images.githubusercontent.com/1475163/149902514-7efafce6-079c-4746-b841-5bce276e4958.png">
<img width="968" alt="CleanShot 2022-01-18 at 10 44 14@2x" src="https://user-images.githubusercontent.com/1475163/149902518-0bb88364-3a16-4bd0-a99a-5f171c0a5ed7.png">

**Comment by alexminza** [comment]
@davidfilat these types of questions related to specific transaction failures should be first and foremost addressed to MAIB support.
