### ISSUE TITLE
maib_close_day scheduled action is not properly registered on certain systems

### ISSUE THREAD

**Issue by tuliuliucroman** [alexminza/wc-moldovaagroindbank#36]
I can't close the financial day, it's not reflected in "Planned actions" - maib_close_day
![image](https://github.com/user-attachments/assets/4ef0c48b-cb68-4ad2-ba79-cfbe0862b713)
![image](https://github.com/user-attachments/assets/1781cab5-a988-4e49-8415-1986f60723d4)

**Comment by alexminza** [comment]
1. See detailed plugin logs
2. Try deactivating / reactivating the plugin to trigger webhook registration

PS: Support questions should be address in the plugin support forum https://wordpress.org/support/plugin/wc-moldovaagroindbank/

**Comment by datalabMD** [comment]
@tuliuliucroman Hello, what version of PHP ?, I suspect what the problem might be :)

**Comment by alexminza** [comment]
@tuliuliucroman @datalabMD try this hotfix from the v1.4.2 branch

* https://github.com/alexminza/wc-moldovaagroindbank/tree/v1.4.2
* https://github.com/alexminza/wc-moldovaagroindbank/pull/37

<img width="822" alt="Screenshot 2024-08-14 at 20 18 27" src="https://github.com/user-attachments/assets/a739c66a-6e33-4b82-a266-517b39497fc0">

**Comment by alexminza** [comment]
Version 1.4.2 was published to WordPress.org Plugin Directory https://wordpress.org/plugins/wc-moldovaagroindbank/
